### ISSUE TITLE
[Feature]: Use Masonry inside a Special HtmlElement Container 

### ISSUE THREAD

**Issue by fisherhuang** [DerYeger/vue-masonry-wall#57]
### Description

I use the plugin with infinity scroll loading, when data loaded the container always scrollto top.

### Solution

I read the source code, found that U use window.scrollY & window.scrollTo. so can U  use Masonry's ParentElement replace window? https://github.com/DerYeger/vue-masonry-wall/blob/8f7e5df839e027ac1586122d530fccaa16898016/src/masonry-wall.vue#L76

### Preferences

- [ ] I want to be assigned to and work on this issue myself

**Comment by DerYeger** [comment]
Thanks for the report!

I don't think using the component's parent element is going to work, since it's possible that an element further up the hierarchy is the scrolling container (like the default `window`).

I could add a new prop, that allows setting a custom scroll container (by passing a `ref`), would that fix your issue?

**Comment by DerYeger** [comment]
With v3.1.0, you can pass a `HTMLElement` with the `scrollContainer` prop to set a custom scroll container.
[The demo](https://vue-masonry-wall.yeger.eu) has a new setting ("Scroll Container") to see it in action.
